Move debug_stream initialization to helper method
kislyuk/argcomplete pull request #471
Opened 2024-01-29 01:09 UTC by azhu-tower

By default argcomplete tries to use fd 9 as its debug stream, but this could clash with something else trying to use the same file descriptor, for example a pytest plugin.

Split into a _init_debug_stream() helper method which can now be overridden in subclasses.

Closes #393

2024-01-29 03:41 UTC, kislyuk requested changes
Thanks. This looks good, except please do not try to edit Changes.rst manually, it is automatically generated. Can you please remove that change from the PR?

2024-01-29 10:58 UTC, azhu-tower commented
Yep updated, got thrown off by the missing bullet point in the most recent entry :)

2024-01-29 15:27 UTC, kislyuk approved these changes

2024-01-29 17:13 UTC, merged

2024-03-08 01:30 UTC, kislyuk commented
Released in v3.2.3, please test